public enum EventDefine
{
    ShowGamePanel,
    ShowGameOverPanel,
    ShowShopPanel,
    ShowMainPanel,
    ShowRankPanel,
    ShowResetPanel,
    ShowLackDiamond,
    PlatformSpawn,
    AddScore,
    UpdateScore,
    PlayerMove,
    UpdateDiamondCount,
    AddDiamondCount,
    ChangeSkin,
    PlayAudio,
    IsMusicOn,
}
